### ISSUE TITLE
Error: Unexpected close tag

### ISSUE THREAD

**Issue by okawaffles** [Xn2/Near-core#5]
When SDVX establishes a connection to the server, it will display an unexpected close tag error in the console.
This happens every time the menu reloads (when idle)

```Error: Unexpected close tag
Line: 50
Column: 9
Char: >
    at error (Near-core\node_modules\sax\lib\sax.js:651:10)
    at strictFail (Near-core\node_modules\sax\lib\sax.js:677:7)
    at closeTag (Near-core\node_modules\sax\lib\sax.js:871:9)
    at SAXParser.write (Near-core\node_modules\sax\lib\sax.js:1436:13)
    at Object.module.exports [as xml2js] (Near-core\node_modules\xml-js\lib\xml2js.js:346:12)
    at decryptHTTP (Near-core\components\libs\crypto.js:21:28)
    at Layer.handle [as handle_request] (Near-core\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (Near-core\node_modules\express\lib\router\index.js:323:13)
    at Near-core\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (Near-core\node_modules\express\lib\router\index.js:341:12)

**Comment by Xn2** [comment]
This is an error that can be disregarded, it's from the game sending whatever telemetry data it does when refreshing the menu. This should not affect the normal functionning of the server.

Meanwhile, ill check what is causing this.
